### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor#2]

**Comment by IzzySoft** [comment]
App will become available [here](https://apt.izzysoft.de/fdroid/index/apk/com.example.textextractor) in about 10h. Some screenshots would be helpful, description potentially needs some updates. Ideally, [Fastlane structures](https://gitlab.com/snippets/1895688) are used for that.

**Comment by IzzySoft** [comment]
So no screenshots, no fastlane? :cry:
