### ISSUE TITLE
No internet connection alert

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor#3]
Add a no internet connection alert

**Comment by AlinaStepanova** [comment]
Hi @Aman-zishan! I can provide this solution:
![Screenshot_1602793269](https://user-images.githubusercontent.com/23102335/96181850-4d588280-0f3d-11eb-8e5c-3110db9ba8d4.png)
If it is fine, please assign the issue to me

**Comment by Aman-zishan** [comment]
Awesome!
