### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [Aman-zishan/textextractor#6]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using an expired debug key ("denyAfter 2019-01-01"). As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
@Aman-zishan Any chance? Or did you abandon development of this app?

**Comment by Aman-zishan** [comment]
Hey! Yes the app is no longer mantained.

**Comment by IzzySoft** [comment]
Thanks for the feedback, @Aman-zishan! I'll then remove it from [my repo](https://apt.izzysoft.de/fdroid). All the best for you, wherever your heart will lead you to!
